
services:
  db:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: prueba
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3008:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck: # <- Healthcheck añadido aquí
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret" ]
      interval: 5s
      timeout: 10s
      retries: 5



  api:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
